version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "5174:5174"
    container_name: ropadigital-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ropadigital

  nginx:
    image: nginx:1.25
    container_name: ropadigital-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - ropadigital

  db:
    image: mysql:8.0
    container_name: ropadigital-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ropadigital
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: ropadigital
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ropadigital

networks:
  ropadigital:
    driver: bridge

volumes:
  dbdata:
