version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "5174:5174"
    container_name: ${APP_NAME:-laravel}-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravue

  nginx:
    image: nginx:1.25
    container_name: ${APP_NAME:-laravel}-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - laravue
    security_opt:
      - no-new-privileges:true
    environment:
      - NGINX_WORKER_PROCESSES=auto
      - NGINX_WORKER_CONNECTIONS=1024
      - NGINX_KEEPALIVE_TIMEOUT=65
      - NGINX_CLIENT_MAX_BODY_SIZE=10M

  db:
    image: mysql:8.0
    container_name: ${APP_NAME:-laravel}-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravue-boilerplate
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravue
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravue

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APP_NAME:-laravel}-phpmyadmin
    ports:
      - "8080:80"
    networks:
      - laravue
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${APP_NAME:-laravel}-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravue

networks:
  laravue:
    driver: bridge

volumes:
  dbdata:
